{
 "title": "ATM_Nodes_Overview_v1",
 "description": "Monitors Kubernetes cluster using Prometheus. Shows overall cluster CPU / Memory / Filesystem usage as well as individual pod, containers, systemd services statistics. Uses cAdvisor metrics only.",
 "tags": [
  "kubernetes",
  "test",
  "ATM"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Node", "query": "label_values(nodename)" },
   {
    "name": "Instance",
    "query": "label_values(kube_pod_info{node=~\"$Node\"}, host_ip)"
   },
   {
    "name": "copy_of_Instance",
    "query": "label_values(kube_pod_info{host_ip=~\"$Instance\"}, node)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster CPU usage (1m avg)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",node=~\"^$Node$\"}[1m])) / sum (machine_cpu_cores{node=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Cluster memory usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",node=~\"^$Node$\"}) / sum (machine_memory_bytes{node=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Cluster filesystem usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\",node=~\"^$Node$\"}) / sum (container_fs_limit_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\",node=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Node Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load1", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Nodes Readness",
   "type": "table",
   "gridPos": { "h": 4, "w": 6, "x": 15, "y": 1 },
   "targets": [
    {
     "expr": "(sum(kube_node_status_condition{condition=\"Ready\",status=~\"true\",node=~\"$Node\"}) by (node,condition))"
    }
   ]
  },
  {
   "title": "PODs Statuses",
   "type": "table",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 1 },
   "targets": [
    {
     "expr": "sum (kube_pod_status_phase{}) by (phase)",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=~\"^/\",node=~\"^$Node$\"}[1m]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{node=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 4 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",node=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 4 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (machine_memory_bytes{node=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 4 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\",node=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 4 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_limit_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\",node=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Node's Problems",
   "type": "table",
   "gridPos": { "h": 3, "w": 6, "x": 15, "y": 5 },
   "targets": [
    {
     "expr": "(sum(kube_node_status_condition{condition!=\"Ready\",status=\"true\",node=~\"$Node\"}) by (node,condition))==1"
    }
   ]
  },
  {
   "title": "ApiServer",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{job=~\"apiserver\"}"
    }
   ]
  },
  {
   "title": "Scheduler",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{job=~\"kube-scheduler\"}"
    }
   ]
  },
  {
   "title": "Control Manager",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{job=~\"kube-controller-manager\"}"
    }
   ]
  },
  {
   "title": "Cluster Health",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 6 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    { "expr": "node_collector_zone_health" }
   ]
  },
  {
   "title": "PODs",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kubelet_running_pod_count{node =~ \"$Node\"})"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kubelet_running_container_count{node =~ \"$Node\"})"
    }
   ]
  },
  { "title": "Graphs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Pods CPU usage (1m avg)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",node=~\"^$Node$\"}[1m])) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    },
    {
     "expr": "sum (node:node_num_cpu:sum{node=~\"^$Node\"})",
     "legendFormat": "Available CPU cores"
    }
   ]
  },
  {
   "title": "Pods memory usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",node=~\"^$Node$\"}) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    },
    {
     "expr": "sum(node:node_memory_bytes_total:sum{node=~\"^$Node\"})",
     "legendFormat": "{{Available Memory}}"
    }
   ]
  },
  {
   "title": "Node's DiskSpace [/dev/*]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_fs_limit_bytes{device=~\"^/dev/.*\",id=\"/\",node=~\"^$Node$\"})",
     "legendFormat": "{{DiskSpace Total}}"
    },
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/.*\",pod_name=~\".+\"}) by (pod_name)"
    }
   ]
  },
  {
   "title": "Pods network I/O (1m avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{node=~\"^$Node$\"}[1m])) by (pod_name)",
     "legendFormat": "-> {{ pod_name }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{node=~\"^$Node$\"}[1m])) by (pod_name)",
     "legendFormat": "<- {{ pod_name }}"
    }
   ]
  },
  {
   "title": "Network I/O pressure",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{node=~\"^$Node$\"}[1m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{node=~\"^$Node$\"}[1m]))",
     "legendFormat": "Sent"
    }
   ]
  }
 ]
}