{
 "title": "ATM_Workloads_v1",
 "description": "Monitors Kubernetes cluster using Prometheus. Shows overall cluster CPU / Memory / Filesystem usage as well as individual pod, containers, systemd services statistics. Uses cAdvisor metrics only.",
 "tags": [
  "kubernetes",
  "test",
  "ATM"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Instance",
    "query": "label_values(kube_pod_info{node=~\"$Node\"}, host_ip)"
   },
   {
    "name": "copy_of_Instance",
    "query": "label_values(kube_pod_info{host_ip=~\"$Instance\"}, node)"
   },
   {
    "name": "Deployment",
    "query": "label_values(kube_deployment_status_replicas, deployment)"
   },
   {
    "name": "POD_old",
    "query": "label_values(kube_pod_info, pod)"
   },
   {
    "name": "WorkLoad",
    "query": "label_values(mixin_pod_workload, workload)"
   },
   {
    "name": "PODs",
    "query": "label_values(mixin_pod_workload{workload=~\"^$WorkLoad\"}, pod)"
   },
   {
    "name": "POD_IP",
    "query": "label_values(kube_pod_info{pod=~\"$PODs\"}, pod_ip)"
   },
   {
    "name": "HOST_IP",
    "query": "label_values(kube_pod_info{pod=~\"$PODs\"}, host_ip)"
   },
   {
    "name": "NODE",
    "query": "label_values(kube_pod_info{pod=~\"$PODs\"}, node)"
   },
   {
    "name": "NAMESPACE",
    "query": "label_values(kube_pod_info{pod=~\"$PODs\"}, namespace)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Resource Info",
   "type": "text",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "content": "<br>WORKLOAD: $WorkLoad\n<br>NAMESPACE : $NAMESPACE\n<br>PODs:\n<br>&emsp;&emsp;-- $PODs\n<br>POD_IPs:\n<br>&emsp;&emsp;-- $POD_IP\n<br>HOST_IPs\n<br>&emsp;&emsp;-- $HOST_IP\n<br>HOST_NAMEs:\n<br>&emsp;&emsp;-- $NODE\n\n\n\n\n\n"
  },
  {
   "title": "PODs Statuses",
   "type": "table",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "sum (kube_pod_status_phase{pod=~\"$PODs\"}) by (phase)",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  { "title": "Graphs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Pods CPU usage (1m avg)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",pod_name=~\"$PODs\"}[1m])) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Pods memory usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",pod_name=~\"$PODs\"}) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Node's DiskSpace [/dev/*]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/.*\",pod_name=~\"^$PODs\"}) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Pods network I/O (1m avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{pod_name=~\"^$PODs\"}[1m])) by (pod_name)",
     "legendFormat": "-> {{ pod_name }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{pod_name=~\"^$PODs\"}[1m])) by (pod_name)",
     "legendFormat": "<- {{ pod_name }}"
    }
   ]
  }
 ]
}